name: Publish NuGet Package

on:
  push:
    tags:
      - 'v1.0.2-beta'  # This triggers the workflow on the v1.0.2-beta tag
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Install dependencies
        run: dotnet restore ./Rembg/Rembg.csproj

      - name: Build the project
        run: dotnet build ./Rembg/Rembg.csproj --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack ./Rembg/Rembg.csproj --configuration Release

      - name: Publish to NuGet
        run: dotnet nuget push /home/runner/work/rembg-dotnet/rembg-dotnet/Rembg/bin/Release/Rembg.1.0.2-beta.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
