name: Publish NuGet Package

on:
  push:
    tags:
      - 'v1.0.2-beta'  # This triggers the workflow on the v1.0.2-beta tag
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Install dependencies
        run: dotnet restore ./Rembg/Rembg.csproj

      - name: Build the project
        run: dotnet build ./Rembg/Rembg.csproj --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack ./Rembg/Rembg.csproj --configuration Release --output ./nuget

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.2-beta
          release_name: 1.0.2-beta
          draft: false
          prerelease: true

      - name: Upload NuGet package to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rembg-dotnet/nuget/Rembg.1.0.2-beta.nupkg
          asset_name: Rembg.1.0.2-beta.nupkg
          asset_content_type: application/zip

      - name: Publish to NuGet
        run: dotnet nuget push ./rembg-dotnet/nuget/Rembg.1.0.2-beta.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
